services:

  mqtt:
    container_name: mqtt
    image: eclipse-mosquitto
    volumes:
      - ./infra/mosquitto/config:/mosquitto/config
      - ./infra/mosquitto/data:/mosquitto/data
      - ./infra/mosquitto/log:/mosquitto/log
    ports:
      - "1883:1883"
      - "9001:9001"

  app:
    container_name: app
    build:
      context: ./app
    volumes:
      - ./app:/app/
